spring:
  application:
    name: auth-service
  profiles:
    active: prod
  mvc:
    dispatch-options-request: false
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  messages:
    encoding: UTF-8

server:
  port: 9001
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${discovery.username}:${discovery.password}@${discovery.host}:${discovery.port}/eureka
