discovery:
  host:
  port:
  username:
  password:

token:
  expiration_time: 600000 # 10 * 60 * 1000
  secret:

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.tcp.jp.ngrok.io:11492/caboomlog
    username: root
    password: dlatpdus21!
  data:
    redis:
      host: 0.tcp.jp.ngrok.io
      port: 15398
      password: dlatpdus21!