spring:
  application:
    name: auth-service
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_APPLICATION_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9001
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
