discovery:
  host:
  port:
  username:
  password:

token:
  expiration_time: 600000 # 10 * 60 * 1000
  secret:

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  data:
    redis:
      host:
      port:
      password: